// SPDX-License-Identifier: FSL-1.1-Apache-2.0
// Copyright (c) 2025 Open Computer Use Contributors

package southface

import (
	"bytes"
	"encoding/json"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/Wide-Moat/ocu-filestore/internal/auditgate"
)

// FuzzUploadMultipartParse asserts SEC-51 on the multipart fileUpload parse
// stage: fed an arbitrary raw multipart body (arbitrary boundary, missing/
// duplicate/oversized parts, truncated closing boundary, garbage), the REAL
// upload path (router -> serveUploadMultipart -> readUploadParams/the parse
// stage) NEVER panics and ALWAYS resolves to a bounded outcome — either a clean
// HTTP 200 success for a body that genuinely matches the frozen wire, or an HTTP
// deny (>= 400) carrying a BoundedReason refusal. A malformed body MUST yield a
// bounded DENY, never a partial accept and never an unbounded allocation: the
// dispatcher is wired with a tiny whole-object ceiling and a tiny per-message
// (params) ceiling so an oversized params field or file body is refused by the
// size gates rather than buffered.
//
// This drives the same production seam the multipart tests drive (newRESTRouter
// -> the real serveUploadMultipart entry), feeding fuzz-generated bytes as the
// request body. It deliberately does NOT duplicate FuzzEnvelope: that fuzzes the
// unary JSON envelope decoder (decodeUnaryEnvelope); this fuzzes the multipart
// transport + params-decode seam, which decodeUnaryEnvelope never sees.
func FuzzUploadMultipartParse(f *testing.F) {
	const fuzzScope = "fs-fuzz"

	// Seed corpus: well-formed and adversarial multipart bodies. The boundary
	// string is part of the fuzzed input so the corpus explores arbitrary
	// boundaries (including ones that collide with the body content).
	f.Add("fuzzBoundary", validParams(fuzzScope, "/up.bin", 8), []byte("ABCDEFGH"), true)  // happy path
	f.Add("fuzzBoundary", validParams(fuzzScope, "/up.bin", 8), []byte("ABCD"), true)      // under-declared
	f.Add("fuzzBoundary", validParams(fuzzScope, "/up.bin", 4), []byte("ABCDEFGH"), true)  // over-declared
	f.Add("fuzzBoundary", validParams(fuzzScope, "/up.bin", 0), []byte("ABCDEFGH"), true)  // declared <= 0
	f.Add("fuzzBoundary", validParams("fs-other", "/up.bin", 8), []byte("ABCDEFGH"), true) // scope mismatch
	f.Add("fuzzBoundary", `{"filesystem_id":`, []byte("ABCDEFGH"), true)                   // truncated params JSON
	f.Add("fuzzBoundary", `{"bogus":1}`, []byte("ABCDEFGH"), true)                         // unknown params field
	f.Add("fuzzBoundary", validParams(fuzzScope, "/up.bin", 8), []byte("ABCDEFGH"), false) // params present, NO file part
	f.Add("x", validParams(fuzzScope, "/up.bin", 8), []byte("ABCDEFGH"), true)             // 1-char boundary
	f.Add("", "", []byte(nil), false)                                                      // empty everything
	f.Add("fuzzBoundary", "", []byte(nil), true)                                           // empty params, empty file

	f.Fuzz(func(t *testing.T, boundary, paramsValue string, fileBytes []byte, includeFilePart bool) {
		body, contentType, ok := buildFuzzMultipart(boundary, paramsValue, fileBytes, includeFilePart)
		if !ok {
			// The boundary was unusable by the encoder (e.g. empty or too long); the
			// encoder, not the parser, rejected it. Nothing to assert on the handler.
			return
		}

		// A tiny dispatcher: a small whole-object ceiling AND a small per-message
		// ceiling, so an oversized params field or file body is refused by the
		// bounded-deny gates rather than buffered without limit.
		eng := newFakeEngine()
		sess := &recordingCeilingsSession{}
		g := &fakeGuard{}
		d := newStreamDispatcher(eng, g, sess, 64)
		d.sizeCeiling = 256 // bound the params-field read (readUploadParams limit)

		r := httptest.NewRequest(http.MethodPost, restBase+string(OpFileUpload), bytes.NewReader(body))
		r.Header.Set("Content-Type", contentType)
		r.ContentLength = int64(len(body))
		ps := PeerScope{FilesystemID: fuzzScope, GrantedIntents: okIntents(), UID: 4242, PID: 7}

		rt := newRESTRouter(d)
		w := httptest.NewRecorder()
		// The harness fails the fuzz on any panic via the testing framework's
		// built-in panic capture; reaching ServeHTTP and returning is the
		// never-panic assertion.
		rt.ServeHTTP(w, r.WithContext(contextWithPeerScope(r.Context(), ps)))

		if w.Code == http.StatusOK {
			// ACCEPT is only legal when the params genuinely decoded to a frame whose
			// declared size matches the streamed file bytes for THIS scope — i.e. a
			// real, non-malformed body. An accept on a malformed body is a partial
			// accept and a bug. Verify the accept is well-founded.
			assertAcceptWellFounded(t, paramsValue, fileBytes, fuzzScope)
			// A success must have staged exactly the declared bytes; the ceilings
			// gauge must balance (no leaked reservation).
			if !sess.balanced() {
				t.Fatalf("accepted upload left the ceilings gauge unbalanced (leaked reservation)")
			}
			return
		}

		// DENY path: every non-200 outcome MUST be a bounded refusal — a real HTTP
		// status >= 400 carrying a BoundedReason body (SEC-51: the HTTP status /
		// refusal is authoritative). It must never be a partial/ambiguous status.
		if w.Code < 400 {
			t.Fatalf("malformed upload yielded non-deny status %d (neither 200 success nor >=400 deny); body %q",
				w.Code, w.Body.String())
		}
		var br boundedReason
		if err := json.Unmarshal(w.Body.Bytes(), &br); err != nil {
			t.Fatalf("deny status %d body is not a BoundedReason JSON: %v (%q)", w.Code, err, w.Body.String())
		}
		if br.ReasonCode == "" {
			t.Fatalf("deny status %d carries an empty reason_code (unbounded/unclassified refusal): %q", w.Code, w.Body.String())
		}
		// A refused upload stages NOTHING (temp+rename atomicity) and leaks no
		// ceiling reservation — the bounded-deny invariant end to end.
		if !sess.balanced() {
			t.Fatalf("denied upload left the ceilings gauge unbalanced (leaked reservation): bytes %d/%d fd %d/%d",
				sess.acquired, sess.released, sess.fdAcquired, sess.fdReleased)
		}
		// The deny audit event landed (audit-before-ack / fail-closed): a deny is a
		// recorded truth, never a silent drop.
		if len(g.events) == 0 {
			t.Fatalf("deny status %d recorded no audit event (silent refusal)", w.Code)
		}
	})
}

// assertAcceptWellFounded fails the fuzz if an HTTP 200 was returned for input
// that is NOT a genuinely well-formed, scope-matching, exactly-sized upload. It
// re-derives the truth independently of the handler: the params must strict-
// decode to a frame whose filesystem_id is the channel scope, whose
// declared_size_bytes is > 0 and equals the streamed byte count. Any accept
// outside that envelope is a partial accept of malformed input.
func assertAcceptWellFounded(t *testing.T, paramsValue string, fileBytes []byte, scope string) {
	t.Helper()
	var p uploadParamsFrame
	dec := json.NewDecoder(bytes.NewReader([]byte(paramsValue)))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&p); err != nil {
		t.Fatalf("HTTP 200 on params that do not strict-decode (partial accept): params=%q err=%v", paramsValue, err)
	}
	var extra json.RawMessage
	if dec.Decode(&extra) == nil {
		t.Fatalf("HTTP 200 on params with a trailing second JSON value (partial accept): params=%q", paramsValue)
	}
	if p.FilesystemID != scope {
		t.Fatalf("HTTP 200 on a foreign-scope params (scope=%q want %q): partial accept", p.FilesystemID, scope)
	}
	if p.DeclaredSizeBytes <= 0 {
		t.Fatalf("HTTP 200 on declared_size_bytes <= 0 (%d): partial accept", p.DeclaredSizeBytes)
	}
	if p.DeclaredSizeBytes != int64(len(fileBytes)) {
		t.Fatalf("HTTP 200 on a size mismatch (declared %d, body %d): partial accept", p.DeclaredSizeBytes, len(fileBytes))
	}
}

// buildFuzzMultipart assembles a multipart/form-data body from fuzz-controlled
// pieces: an arbitrary boundary, an arbitrary "params" field value, optional
// file bytes, and whether the file part is emitted at all. ok=false means the
// encoder itself rejected the boundary (so there is no handler input to test).
// The encoder may legitimately reject a malformed boundary — that is the
// transport refusing, not the parser, and there is nothing to assert.
func buildFuzzMultipart(boundary, paramsValue string, fileBytes []byte, includeFilePart bool) (body []byte, contentType string, ok bool) {
	var buf bytes.Buffer
	mw := multipart.NewWriter(&buf)
	if err := mw.SetBoundary(boundary); err != nil {
		return nil, "", false
	}
	// The params FIELD is always written (the parser's first NextPart expects it);
	// the fuzzer controls its value, including empty/garbage/oversized.
	if err := mw.WriteField(multipartParamsFieldName, paramsValue); err != nil {
		return nil, "", false
	}
	if includeFilePart {
		fw, err := mw.CreateFormFile(multipartFileFieldName, multipartFileFilename)
		if err != nil {
			return nil, "", false
		}
		if _, err := fw.Write(fileBytes); err != nil {
			return nil, "", false
		}
	}
	if err := mw.Close(); err != nil {
		return nil, "", false
	}
	return buf.Bytes(), mw.FormDataContentType(), true
}

// validParams marshals a frozen-shape upload params JSON for the seed corpus (a
// write-intent create-new frame with the given scope/path/declared size).
func validParams(scope, path string, declared int64) string {
	p := uploadParamsFixture{
		FilesystemID:          scope,
		Path:                  path,
		DeclaredSizeBytes:     declared,
		AuthorizationMetadata: writeMeta(),
	}
	raw, err := json.Marshal(p)
	if err != nil {
		panic(err) // a seed-corpus marshal failure is a test-author bug, surfaced loudly
	}
	return string(raw)
}

// Compile-time anchor: the fuzz drives the same audit type the multipart suite
// asserts against, so a deny event shape change is caught by the build.
var _ = auditgate.FileActivityEvent{}
